(function e$$0(a,l,e){function n(m,d){if(!l[m]){if(!a[m]){var g="function"==typeof require&&require;if(!d&&g)return g(m,!0);if(b)return b(m,!0);g=Error("Cannot find module '"+m+"'");throw g.code="MODULE_NOT_FOUND",g;}g=l[m]={exports:{}};a[m][0].call(g.exports,function(d){var b=a[m][1][d];return n(b?b:d)},g,g.exports,e$$0,a,l,e)}return l[m].exports}for(var b="function"==typeof require&&require,d=0;d<e.length;d++)n(e[d]);return n})({1:[function(h,a,l){(function(e){var n=h("xhr"),b;for(b in React.DOM)e[b]=
React.DOM[b];var d=React.createClass({displayName:"Search",getInitialState:function(){return{active_page:0,search_results:[],search_filter_type:"title"}},componentDidMount:function(){function d(){var e=document.getElementById("search_filter_text");n.get("/get_entries_by_"+b.search_filter_type+"/"+encodeURI(e&&e.value||"*"),function(e,c){b.search_results=JSON.parse(c.body);g.forceUpdate();setTimeout(d,250)})}var b=this.state,g=this;setTimeout(d,1E3)},render:function(){function d(c){return function(){var d=
{title:document.getElementById("entry_title_input").value,author:document.getElementById("entry_author_input").value};n.post("/"+c+"_entry/"+encodeURI(JSON.stringify(d)),function(c,d){});"del"===c&&b()}}function b(){document.getElementById("entry_title_input").value="";document.getElementById("entry_author_input").value=""}var e=this,k=this.state,a=["Busca","Cataloga\u00e7\u00e3o"],c=k.search_results.map(function(c){return div({className:"search_result"},[div({className:"search_result_title",onClick:function(){k.active_page=
1;e.forceUpdate();setTimeout(function(){document.getElementById("entry_title_input").value=c.title;document.getElementById("entry_author_input").value=c.author},100)}},c.title),div({className:"search_result_author"},[span({className:"search_result_author_by"},"by "),span({className:"search_result_author_name"},c.author)])])}),c=[div({className:"search_page"},[div({className:"search_filter"},[select({className:"search_filter_type",onChange:function(c){k.search_filter_type=c.target.value}},[option({value:"title"},
"T\u00edtulo"),option({value:"author"},"Autoria")]),input({id:"search_filter_text",className:"search_filter_text",key:"search_filter_text"})]),div({className:"search_results_container"},div({className:"search_results"},c))]),div({className:"entry_page"},[div({className:"entry_row"},[span({className:"entry_title"},"T\u00edtulo"),input({className:"entry_text",id:"entry_title_input",key:"entry_title_input"})]),div({className:"entry_row"},[span({className:"entry_title"},"Author"),input({className:"entry_text",
id:"entry_author_input",key:"entry_author_input"})]),div({className:"entry_buttons"},[div({className:"entry_button_row"},[input({type:"submit",className:"entry_button",value:"Enviar",onClick:d("add")}),input({type:"submit",className:"entry_button",value:"Limpar",onClick:b})]),div({className:"entry_button_row"},[input({type:"submit",className:"entry_button",value:"Editar",onClick:d("edit")}),input({type:"submit",className:"entry_button",value:"Excluir",onClick:d("del")})])])])];return div({className:"page"},
[div({className:"page_title",onClick:function(){k.active_page=(k.active_page+1)%a.length;console.log(k);e.forceUpdate()}},a[k.active_page]),c[k.active_page]])}});window.onload=function(){ReactDOM.render(React.createElement(d,{name:"World"}),document.getElementById("main"))}}).call(this,"undefined"!==typeof global?global:"undefined"!==typeof self?self:"undefined"!==typeof window?window:{})},{xhr:8}],2:[function(h,a,l){var e=h("is-function");a.exports=function(d,m,a){if(!e(m))throw new TypeError("iterator must be a function");
3>arguments.length&&(a=this);if("[object Array]"===n.call(d))for(var g=a,k=0,h=d.length;k<h;k++)b.call(d,k)&&m.call(g,d[k],k,d);else if("string"===typeof d)for(g=a,k=0,h=d.length;k<h;k++)m.call(g,d.charAt(k),k,d);else for(k in g=a,d)b.call(d,k)&&m.call(g,d[k],k,d)};var n=Object.prototype.toString,b=Object.prototype.hasOwnProperty},{"is-function":4}],3:[function(h,a,l){h="undefined"!==typeof global?global:"undefined"!==typeof self?self:"undefined"!==typeof window?window:{};a.exports="undefined"!==
typeof window?window:"undefined"!==typeof h?h:"undefined"!==typeof self?self:{}},{}],4:[function(h,a,l){a.exports=function(a){var b=e.call(a);return"[object Function]"===b||"function"===typeof a&&"[object RegExp]"!==b||"undefined"!==typeof window&&(a===window.setTimeout||a===window.alert||a===window.confirm||a===window.prompt)};var e=Object.prototype.toString},{}],5:[function(h,a,l){function e(a){var b=!1;return function(){if(!b)return b=!0,a.apply(this,arguments)}}a.exports=e;e.proto=e(function(){Object.defineProperty(Function.prototype,
"once",{value:function(){return e(this)},configurable:!0})})},{}],6:[function(h,a,l){var e=h("trim"),n=h("for-each");a.exports=function(b){if(!b)return{};var d={};n(e(b).split("\n"),function(b){var a=b.indexOf(":"),g=e(b.slice(0,a)).toLowerCase();b=e(b.slice(a+1));"undefined"===typeof d[g]?d[g]=b:"[object Array]"===Object.prototype.toString.call(d[g])?d[g].push(b):d[g]=[d[g],b]});return d}},{"for-each":2,trim:7}],7:[function(h,a,l){l=a.exports=function(a){return a.replace(/^\s*|\s*$/g,"")};l.left=
function(a){return a.replace(/^\s*/,"")};l.right=function(a){return a.replace(/\s*$/,"")}},{}],8:[function(h,a,l){function e(c){for(var d in c)if(c.hasOwnProperty(d))return!1;return!0}function n(c,d,b){var a=c;g(d)?(b=d,"string"===typeof c&&(a={uri:c})):a=x(d,{uri:c});a.callback=b;return a}function b(c,a,b){a=n(c,a,b);return d(a)}function d(c){function a(c){clearTimeout(r);c instanceof Error||(c=Error(""+(c||"Unknown XMLHttpRequest Error")));c.statusCode=0;g(c,h)}function d(){if(!l){var a;clearTimeout(r);
a=c.useXDR&&void 0===f.status?200:1223===f.status?204:f.status;var b=h,e=null;if(0!==a){b=void 0;f.response?b=f.response:"text"!==f.responseType&&f.responseType||(b=f.responseText||f.responseXML);if(u)try{b=JSON.parse(b)}catch(m){}b={body:b,statusCode:a,method:q,headers:{},url:n,rawRequest:f};f.getAllResponseHeaders&&(b.headers=k(f.getAllResponseHeaders()))}else e=Error("Internal XMLHttpRequest Error");g(e,b,b.body)}}var g=c.callback;if("undefined"===typeof g)throw Error("callback argument missing");
var g=w(g),h={body:void 0,headers:{},statusCode:0,method:q,url:n,rawRequest:f},f=c.xhr||null;f||(f=c.cors||c.useXDR?new b.XDomainRequest:new b.XMLHttpRequest);var m,l,n=f.url=c.uri||c.url,q=f.method=c.method||"GET",v=c.body||c.data||null,p=f.headers=c.headers||{},t=!!c.sync,u=!1,r;"json"in c&&(u=!0,p.accept||p.Accept||(p.Accept="application/json"),"GET"!==q&&"HEAD"!==q&&(p["content-type"]||p["Content-Type"]||(p["Content-Type"]="application/json"),v=JSON.stringify(c.json)));f.onreadystatechange=function(){4===
f.readyState&&d()};f.onload=d;f.onerror=a;f.onprogress=function(){};f.ontimeout=a;f.open(q,n,!t,c.username,c.password);t||(f.withCredentials=!!c.withCredentials);!t&&0<c.timeout&&(r=setTimeout(function(){l=!0;f.abort("timeout");var c=Error("XMLHttpRequest timeout");c.code="ETIMEDOUT";a(c)},c.timeout));if(f.setRequestHeader)for(m in p)p.hasOwnProperty(m)&&f.setRequestHeader(m,p[m]);else if(c.headers&&!e(c.headers))throw Error("Headers cannot be set on an XDomainRequest object");"responseType"in c&&
(f.responseType=c.responseType);"beforeSend"in c&&"function"===typeof c.beforeSend&&c.beforeSend(f);f.send(v);return f}function m(){}l=h("global/window");var w=h("once"),g=h("is-function"),k=h("parse-headers"),x=h("xtend");a.exports=b;b.XMLHttpRequest=l.XMLHttpRequest||m;b.XDomainRequest="withCredentials"in new b.XMLHttpRequest?b.XMLHttpRequest:l.XDomainRequest;(function(c,a){for(var b=0;b<c.length;b++)a(c[b])})("get put post patch head delete".split(" "),function(c){b["delete"===c?"del":c]=function(b,
a,e){a=n(b,a,e);a.method=c.toUpperCase();return d(a)}})},{"global/window":3,"is-function":4,once:5,"parse-headers":6,xtend:9}],9:[function(h,a,l){a.exports=function(){for(var a={},b=0;b<arguments.length;b++){var d=arguments[b],h;for(h in d)e.call(d,h)&&(a[h]=d[h])}return a};var e=Object.prototype.hasOwnProperty},{}]},{},[1]);
